version: '3.8'

services:
  # caddy:
  #   image: caddy:2
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #     - "2019:2019"
  #   volumes:
  #     - .docker/caddy/Caddyfile:/etc/caddy/Caddyfile
  #     - ./data/caddy/data:/data
  #     - ./data/caddy/config:/config

  nginx:
    image: nginx:1.21-alpine
    container_name: "devbox-nginx"
    ports:
      - "8080:80"
    volumes:
      - $PWD/.docker/nginx/conf.d:/etc/nginx/conf.d
      - $PHP74_PATH:/webapps/php74
      - $PHP80_PATH:/webapps/php80
    links:
      - php74
      - php80
    command: "nginx-debug -g 'daemon off;'"

  php74:
    build:
      context: .docker/php74
    container_name: "devbox-php74"
    restart: unless-stopped
    volumes:
      - $PHP74_PATH:/webapps/php74

  php80:
    image: php:8.0-fpm-alpine
    container_name: "devbox-php80"
    restart: unless-stopped
    volumes:
      - $PHP80_PATH:/webapps/php80

# - https://newbedev.com/how-to-setup-mass-dynamic-virtual-hosts-in-nginx
# - https://tech.osteel.me/posts/docker-for-local-web-development-part-1-a-basic-lemp-stack
# - http://geekyplatypus.com/dockerise-your-php-application-with-nginx-and-php7-fpm/
# - http://geekyplatypus.com/making-your-dockerised-php-application-even-better/ -- continued from previous link
