version: '3.8'

services:
  dnsmasq:
    image: jpillora/dnsmasq:latest
    container_name: devbox-dnsmasq
    ports:
      - "53:53/udp"
      - "5380:8080"
    environment:
      - "HTTP_USER=foo"
      - "HTTP_PASS=bar"
    volumes:
      - .docker/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf

  nginx:
    image: nginx:1.21-alpine
    container_name: "devbox-nginx"
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - $PWD/.docker/nginx/conf.d:/etc/nginx/conf.d
      - $PHP74_PATH:/webapps/php74
      - $PHP80_PATH:/webapps/php80
    links:
      - php74
      - php80
    command: "nginx-debug -g 'daemon off;'"

  php74:
    build:
      context: .docker/php74
    container_name: "devbox-php74"
    volumes:
      - $PHP74_PATH:/webapps/php74

  php80:
    build: 
      context: .docker/php80
    container_name: "devbox-php80"
    volumes:
      - $PHP80_PATH:/webapps/php80

# - https://newbedev.com/how-to-setup-mass-dynamic-virtual-hosts-in-nginx
# - https://tech.osteel.me/posts/docker-for-local-web-development-part-1-a-basic-lemp-stack
# - http://geekyplatypus.com/dockerise-your-php-application-with-nginx-and-php7-fpm/
# - http://geekyplatypus.com/making-your-dockerised-php-application-even-better/ -- continued from previous link
